#############################################################################
# Makefile for building: libHSImage.so.1.0.0
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  HSImage.pro
# Template: lib
# Command: /home/joshua/Software/Qt/5.8/gcc_64/bin/qmake -o Makefile HSImage.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHSIMAGE_LIBRARY -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/python3.5 -IINCLUDEPATH -I=+ -isystem /usr/include/boost -I../../../Software/Qt/5.8/gcc_64/include -I../../../Software/Qt/5.8/gcc_64/include/QtCore -I. -I../../../Software/Qt/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/joshua/Software/Qt/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HSImage1.0.0
DISTDIR = /home/joshua/Repositories/GitLabRepos/HSImage/.tmp/HSImage1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/joshua/Software/Qt/5.8/gcc_64/lib -shared -Wl,-soname,libHSImage.so.1
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lboost_system -lboost_python3 -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5 -L/home/joshua/Software/Qt/5.8/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = hsimage.cpp \
		classifiedhsimage.cpp \
		target.cpp \
		colormap.cpp 
OBJECTS       = hsimage.o \
		classifiedhsimage.o \
		target.o \
		colormap.o
DIST          = ../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		HSImage.pro hsimage.h \
		hsimage_global.h \
		classifiedhsimage.h \
		annEnums.h \
		target.h \
		colormap.h hsimage.cpp \
		classifiedhsimage.cpp \
		target.cpp \
		colormap.cpp
QMAKE_TARGET  = HSImage
DESTDIR       = 
TARGET        = libHSImage.so.1.0.0
TARGETA       = libHSImage.a
TARGET0       = libHSImage.so
TARGETD       = libHSImage.so.1.0.0
TARGET1       = libHSImage.so.1
TARGET2       = libHSImage.so.1.0


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: HSImage.pro ../../../Software/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../Software/Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		HSImage.pro \
		../../../Software/Qt/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile HSImage.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/unix.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/linux.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/qconfig.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/default_post.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/qt.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/resources.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/moc.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/yacc.prf:
../../../Software/Qt/5.8/gcc_64/mkspecs/features/lex.prf:
HSImage.pro:
../../../Software/Qt/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile HSImage.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Software/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents hsimage.h hsimage_global.h classifiedhsimage.h annEnums.h target.h colormap.h $(DISTDIR)/
	$(COPY_FILE) --parents hsimage.cpp classifiedhsimage.cpp target.cpp colormap.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Software/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../Software/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

hsimage.o: hsimage.cpp hsimage.h \
		hsimage_global.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hsimage.o hsimage.cpp

classifiedhsimage.o: classifiedhsimage.cpp classifiedhsimage.h \
		hsimage.h \
		hsimage_global.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../Software/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		colormap.h \
		annEnums.h \
		target.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classifiedhsimage.o classifiedhsimage.cpp

target.o: target.cpp target.h \
		annEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o target.o target.cpp

colormap.o: colormap.cpp colormap.h \
		annEnums.h \
		target.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colormap.o colormap.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/lib || mkdir -p $(INSTALL_ROOT)/usr/local/lib
	-$(INSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/lib/ 


install_headers: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/include || mkdir -p $(INSTALL_ROOT)/usr/local/include
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/hsimage.h $(INSTALL_ROOT)/usr/local/include/
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/hsimage_global.h $(INSTALL_ROOT)/usr/local/include/
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/classifiedhsimage.h $(INSTALL_ROOT)/usr/local/include/
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/annEnums.h $(INSTALL_ROOT)/usr/local/include/
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/target.h $(INSTALL_ROOT)/usr/local/include/
	-$(INSTALL_FILE) /home/joshua/Repositories/GitLabRepos/HSImage/colormap.h $(INSTALL_ROOT)/usr/local/include/

uninstall_headers: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/colormap.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/target.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/annEnums.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/classifiedhsimage.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/hsimage_global.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/hsimage.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/include/ 


install: install_target install_headers  FORCE

uninstall: uninstall_target uninstall_headers  FORCE

FORCE:

